### ISSUE TITLE
Add GRKERNSEC_LOGSPOOF

### ISSUE THREAD

**Issue by theLOICofFRANCE** [minipli/linux-unofficial_grsec#1]
Hi,

What do you think about adding this feature?

[grsec_logspoof-4.9.x.txt](https://github.com/minipli/linux-unofficial_grsec/files/1031979/grsec_logspoof-4.9.x.txt)

Thank you. Best regards

**Comment by minipli** [comment]
It would be an extension to the status quo and therefore beyond the scope of this repo.

I'm sorry, but this repo is not meant for grsec development. You have to carry that patch yourself.
