### ISSUE TITLE
any plans to port the patch for a newer kernel?

### ISSUE THREAD

**Issue by blshkv** [minipli/linux-unofficial_grsec#10]
We are having an internal debates and I was wondering would you be porting the patch for a newer kernel?
Any plans/works so far?

**Comment by theLOICofFRANCE** [comment]
Hi,

No, he won't do it.

https://github.com/minipli/linux-unofficial_grsec/wiki

**Comment by minipli** [comment]
As @HacKurx already mentioned, that questions is answered in the [FAQ](https://github.com/minipli/linux-unofficial_grsec/wiki#kernel-v49x-is-kinda-old-i-need-a-newer-one-are-you-going-to-forward-port-the-patch-to-the-next-lts-kernel-eg-to-v414).

**Comment by blshkv** [comment]
sad to hear. Thank you anyway
