### ISSUE TITLE
Add GRKERNSEC_RANDOM_TIMESTAMPS

### ISSUE THREAD

**Issue by theLOICofFRANCE** [minipli/linux-unofficial_grsec#2]
Hi,

What do you think about adding this feature?

[random_timestamp-4.9.x.txt](https://github.com/minipli/linux-unofficial_grsec/files/1031993/random_timestamp-4.9.x.txt)

Thank you. Best regards

**Comment by minipli** [comment]
Same as for issue #1, it's beyond the scope of this repo.
I'm sorry, but you have to carry this one yourself, too.
