### ISSUE TITLE
Static link for scripted download

### ISSUE THREAD

**Issue by Esokrates** [minipli/linux-unofficial_grsec#3]
Could you somehow provide a way to discover the latest version of the patch (diff file) from a script? Grsecurity originally provided a static link to a text file containing the name of the latest patch, but I guess this is not possible here given the possibilities of github?

**Comment by parazyd** [comment]
You can use github's RSS feed to see when a new patch is tagged.

**Comment by Esokrates** [comment]
I have found a way :-):
`curl -s https://api.github.com/repos/minipli/linux-unofficial_grsec/releases/latest | jq -r ".assets[].name" | head -1`

I am closing this now.
