### ISSUE TITLE
4.9.34+

### ISSUE THREAD

**Issue by jaccc** [minipli/linux-unofficial_grsec#5]
is there some problem after 4.9.33 ?

**Comment by HacKurx** [comment]
Personally I started to look it (for 4.9.36) :
http://dl.free.fr/k2f5fHWpr

**Comment by theLOICofFRANCE** [comment]
Can be replace sun and vacation? ^^

I maked a version for linux 4.9.36.
Kernel: https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.36.tar.xz
Patch: http://dl.free.fr/i36vyumFN

But I did not take into account all the latest changes of the kernel to make it simple and not to break all.

**Comment by minipli** [comment]
Thank you all. I was on vacation and had no time to do the porting. Sorry...
Releases for v4.9.34 to v4.9.37 have been pushed just yet.

**Comment by theLOICofFRANCE** [comment]
@minipli 
Thank you very much.
